"""Add jetton holder models

Revision ID: de10d5cc2c6b
Revises: 
Create Date: 2024-09-06 22:40:57.324011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de10d5cc2c6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jetton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jetton_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jetton_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jetton_decimals', sa.Integer(), nullable=False),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jettonholder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holder_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('jetton_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jetton_id'], ['jetton.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('jetton_holder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jetton_holder_id'], ['jettonholder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    op.drop_table('jettonholder')
    op.drop_table('jetton')
    # ### end Alembic commands ###
